In [15]:
import numpy as np

A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]])
print(A)

cal = A.sum(axis=0)
#cal.reshape(1,4)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [16]:
percentage = 100 * A / cal
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [22]:
x = np.random.randn(3,3)
y = np.random.randn(3,1)
c = np.dot(x,y) #x*y
print(c)

[[-1.34157499]
 [-0.24264068]
 [-0.29886354]]
