# Python Numpy Vectors

In [14]:
import numpy as np

A = np.random.randn(5) #DON'T USE THIS
print(A)
print(A.shape)

[ 1.31633691  0.68316884 -0.01082682 -0.57547569 -0.49628221]
(5,)


In [15]:
B = np.random.randn(5,1)
print(B)
print(B.shape)

[[ 0.60423713]
 [ 0.37477243]
 [ 0.67184514]
 [-1.11750803]
 [-1.53408104]]
(5, 1)


In [16]:
print(B.T)
print()

[[ 0.60423713  0.37477243  0.67184514 -1.11750803 -1.53408104]]



In [21]:
RES = np.dot(B,B.T)
print(RES)

[[ 0.36510251  0.22645141  0.40595377 -0.67523984 -0.92694872]
 [ 0.22645141  0.14045437  0.25178903 -0.4188112  -0.57493127]
 [ 0.40595377  0.25178903  0.45137589 -0.75079234 -1.03066489]
 [-0.67523984 -0.4188112  -0.75079234  1.24882421  1.71434789]
 [-0.92694872 -0.57493127 -1.03066489  1.71434789  2.35340465]]


In [30]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.zeros(shape=(3,4))

print(a)
print()
print(b)
print()

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
        
print(c)

[[ 0.11593224  0.86970293 -0.35387703 -0.53863342]
 [-0.84210181 -0.18691459 -0.80689905  0.63456913]
 [ 0.58792237  0.4487683  -0.22547156 -0.8014756 ]]

[[ 1.59188882]
 [ 1.75450983]
 [-2.09919689]
 [ 0.87445931]]

[[ 1.70782106  2.62421276 -2.45307393  0.33582588]
 [ 0.74978701  1.56759524 -2.90609594  1.50902844]
 [ 2.17981119  2.20327813 -2.32466846  0.0729837 ]]


In [33]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.zeros(shape=(3,4))

print(a)
print()
print(b)
print()

c = a + b.T
print(c)

[[ 1.84307881  0.83509708  1.36376763 -0.4965744 ]
 [ 0.75960355 -0.85262861  0.13642833  0.143089  ]
 [-0.63213219  0.27629616  0.26058756  0.53200483]]

[[ 1.33470547]
 [ 1.49938581]
 [-0.91395282]
 [-0.71171707]]

[[ 3.17778428  2.33448289  0.44981481 -1.20829146]
 [ 2.09430901  0.6467572  -0.77752449 -0.56862807]
 [ 0.70257328  1.77568198 -0.65336526 -0.17971224]]


In [36]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
#c = a*b #error
#print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [37]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c = a + b 
print(c)

[[-0.75786905 -0.08754841  0.26913668]
 [ 0.77254857 -0.17542918  1.70460067]]
